# Generated by Django 4.2.5 on 2023-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("poster", models.ImageField(upload_to="posters/")),
                ("overview", models.TextField(default="Nil")),
                ("genre", models.CharField(max_length=256)),
                ("language", models.CharField(max_length=50)),
                ("runtime", models.CharField(max_length=50)),
                ("ratings", models.IntegerField(null=True)),
                ("status", models.CharField(default="Upcoming", max_length=100)),
                ("release_date", models.DateField()),
            ],
        ),
    ]
