# Generated by Django 4.2.5 on 2023-10-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="casts",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
