# Generated by Django 4.2.5 on 2023-10-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_casts_movie_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="ratings",
            field=models.FloatField(null=True),
        ),
    ]
